# Generated by Django 3.2.15 on 2022-08-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vaga', models.CharField(max_length=50)),
                ('salario', models.CharField(choices=[(1, 'Até 1.000'), (2, 'De 1.000 até 2.000'), (3, 'De 2.000 até 3.000'), (4, 'Acima de 3.000')], max_length=20)),
                ('requisitos', models.CharField(max_length=250)),
                ('escolaridade_minima', models.CharField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós/MBA/Mestrado'), (6, 'Doutorado')], default='', max_length=20)),
            ],
        ),
    ]
