# Generated by Django 3.2.15 on 2022-08-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_vaga_escolaridade_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='candidatos',
            field=models.CharField(default='', max_length=50),
        ),
    ]
