# Generated by Django 3.2.15 on 2022-08-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_vaga_candidatos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaga',
            old_name='candidatos',
            new_name='_candidatos',
        ),
    ]
