# Generated by Django 3.2.15 on 2022-08-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_candidatos_vaga__candidatos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='_candidatos',
        ),
        migrations.CreateModel(
            name='InscricoesVagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretensao_salarial', models.CharField(choices=[(1, 'Até 1.000'), (2, 'De 1.000 até 2.000'), (3, 'De 2.000 até 3.000'), (4, 'Acima de 3.000')], max_length=20)),
                ('experiencia', models.CharField(max_length=300)),
                ('ultima_escolaridade', models.CharField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Médio'), (3, 'Tecnólogo'), (4, 'Ensino Superior'), (5, 'Pós/MBA/Mestrado'), (6, 'Doutorado')], max_length=15)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vaga')),
            ],
        ),
    ]
